import type { Listing, Vehicle } from './types'
import { mockVehicles } from './mock-data'

export const mercedesMedia = {
  cClassStudio: 'https://media.oneweb.mercedes-benz.com/images/dynamic/europe/DE/118384/806_056/iris.png?BKGND=9&IMGT=P27&POV=BE040%2CPZM&cp=U7lLKRUtPa6KAFr8s_ubHw&q=COSY-EU-100-1713d0VXq5SFqtyO67PobzIr3eWsrrCsdRRzwQZxkIZbMw3SGtGyUtsd2sDcUfpOcXGEundJ0l3okOB2NbFbApRARI5ux6YQC3aM3kzNHmwm7j8h1hKVitF%25vqmtjyLRhAmYaxU5drH1Gc%25n8w7O4oiZK%25oM4FvOwTg9Ukm6tTnuNpHOhKVU0b%25vqLvkyLRaOXYaxHNhrHAlGqhTWFEnlAyK71G1JnwxV4V%25d%25CWLH59zW0uBZTmGaX&uni=m',
  claStudio: 'https://media.oneweb.mercedes-benz.com/images/dynamic/europe/DE/118384/806_056/iris.png?BKGND=9&IMGT=P27&POV=BE040%2CPZM&cp=U7lLKRUtPa6KAFr8s_ubHw&q=COSY-EU-100-1713d0VXq5SFqtyO67PobzIr3eWsrrCsdRRzwQZxkIZbMw3SGtGyUtsd2sDcUfpOcXGEundJ0l3okOB2NbFbApRARI5ux6YQC3aM3kzNHmwm7j8h1hKVitF%25vqmtjyLRhAmYaxU5drH1Gc%25n8w7O4oiZK%25oM4FvOwTg9Ukm6tTnuNpHOhKVU0b%25vqLvkyLRaOXYaxHNhrHAlGqhTWFEnlAyK71G1JnwxV4V%25d%25CWLH59zW0uBZTmGaX&uni=m',
  eClassEstateStudio: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/eqe/saloon-v295-pi/overview/spa-highlights/02-2025/images/mercedes-benz-eqe-v295-spa-highlights-exterior-2400x2400-02-2025.jpg?im=Resize%2Cwidth%3D1184',
  glcStudio: 'https://media.oneweb.mercedes-benz.com/images/dynamic/europe/DE/254602/806_056/iris.png?BKGND=9&IMGT=P27&POV=BE320%2CPZM&cp=U7lLKRUtPa6KAFr8s_ubHw&q=COSY-EU-100-1713d0VXq5WFqtyO67PobzIr3eWsrrCsdRRzwQZQ9vZbMw3SGtGyUtsd1JpcUfwFuXGEZT3J0l30fOB2Ng1bApjkbI5uV6JQC3qSpkzNRmdm7jZ6qhKVFKF%25vq9UTyLRDGfYaxWoErH1dItn8wfQ2oiZEqpM4FlRjTg926n6PD87bSeWiwWtsd4oVcUfC%25NXGEzyEJ0l7HfOB2KgFbApvPlI5uLQxQC3akWkzNHmxm7jQ63hKVk0Q%25vqmIlyLRscWYaxU0YrH1GBln8w0Q3oiZBklM4FAs2Tg95bn6PDaksSeWHXutsd8ZDcUfiMcXGE4TBJ0lgCVOB2Pz%25bApe7bI5usKDQC3UnpkzNpTwm7ju6ohKV3YQ%25vq8tTyLRiO6Yax4bJrH1gObnMr%25E2fKtI5ue6xQC3PsXkzN5zNm7jC7DhKVzYV%25vq7rcyLRK3fYaxvJDrH1LPEn8wuOcoiZ3%25ZM4FgIJTg9Pg26PDePoSeWsKMtsdUHVcUaqKDTb32VXq0EeDV9f%25XEd9B96N683eUHpi3v1LlbMKsh&uni=m',
  glcExterior: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/glc/glc-suv-x254-fl-pi/overview/spa-highlights/02-2025/images/mercedes-benz-glc-suv-x254-spa-highlights-exterior-2400x2400-02-2025.jpg?im=Resize%2Cwidth%3D1184',
  gleStudio: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/gle/gle-suv-v167-fl-pi/overview/spa/08-2025/images/mercedes-benz-gle-v167-spa-plug-in-hybrid-2400x2400-08-2025.jpg?im=Resize%2Cwidth%3D1014',
  gleExterior: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/gle/gle-suv-v167-fl-pi/overview/spa/08-2025/images/mercedes-benz-gle-v167-spa-plug-in-hybrid-2400x2400-08-2025.jpg?im=Resize%2Cwidth%3D1014',
  glaExterior: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/gla/gla-suv-h247-fl-pi/overview/spa-highlights/05-2025/images/mercedes-benz-gla-h247-spa-gla-suv-2400x2400-05-2025.jpg?im=Resize%2Cwidth%3D1184',
  eqeStudio: 'https://media.oneweb.mercedes-benz.com/images/dynamic/europe/DE/295111/806_056/iris.png?BKGND=9&IMGT=P27&POV=BE040%2CPZM&cp=U7lLKRUtPa6KAFr8s_ubHw&q=COSY-EU-100-1713d0VXqaSFqtyO67PobzIr3eWsrrCsdRRzwQZQ9vZbMw3SGtGyUtsd2sDcUfp8qXGEu5EJ0l3CrOB2qrnbApRiyI5ux6YQC30E3kzNHzxm7j8G3hKVk0Q%25vqe6kyLR5cHYaxCNqrH1zntn8w7PcoiZKJ1M4FsmJTg9Ukm6tTnuNpHOhKV0XM%25vqGBIyLRKLfYax25JrH18H%25n8wiAyoiCpBxySfD2MpgT0gOfZbMFwRPRYEY7fHizWKfAN59S%25B8O&uni=m',
  eqeExterior: 'https://www.mercedes-benz.de/content/dam/hq/passengercars/cars/eqe/saloon-v295-pi/overview/spa-highlights/02-2025/images/mercedes-benz-eqe-v295-spa-highlights-exterior-2400x2400-02-2025.jpg?im=Resize%2Cwidth%3D1184',
} as const

type InventoryVehicleOverride = Pick<
  Vehicle,
  'make' | 'model' | 'year' | 'vin' | 'color' | 'mileage' | 'fuelType' | 'transmission' | 'power' | 'price' | 'purchasePrice' | 'imageUrl' | 'notes'
> & {
  historyNotes?: Array<string | undefined>
}

const inventoryVehicleOverrides: Record<string, InventoryVehicleOverride> = {
  v1: {
    make: 'Mercedes-Benz',
    model: 'C 220 d T-Modell',
    year: 2022,
    vin: 'W1K2062041F123456',
    color: 'Graphitgrau metallic',
    mileage: 45200,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 200,
    price: 34900,
    purchasePrice: 28500,
    imageUrl: mercedesMedia.cClassStudio,
    notes: 'Bremsen hinten erneuern, Service B inklusive AdBlue-Check einplanen',
  },
  v2: {
    make: 'Mercedes-Benz',
    model: 'C 200 Limousine',
    year: 2023,
    vin: 'W1K2060421A234567',
    color: 'Obsidianschwarz metallic',
    mileage: 22100,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 204,
    price: 38500,
    purchasePrice: 31200,
    imageUrl: mercedesMedia.cClassStudio,
    notes: 'Aufbereitung: Politur, Lederpflege und Stern-Haube nacharbeiten',
  },
  v3: {
    make: 'Mercedes-Benz',
    model: 'CLA 250 e Coupé',
    year: 2023,
    vin: 'W1K1183841N345678',
    color: 'Kosmosschwarz metallic',
    mileage: 37700,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 218,
    price: 32900,
    purchasePrice: 25800,
    imageUrl: mercedesMedia.claStudio,
    notes: 'AMG Line und Night-Paket im Exposé hervorheben',
  },
  v4: {
    make: 'Mercedes-Benz',
    model: 'A 200 Limousine',
    year: 2023,
    vin: 'W1K1770871J456789',
    color: 'Polarweiß',
    mileage: 18500,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 163,
    price: 31500,
    purchasePrice: 25900,
    imageUrl: mercedesMedia.claStudio,
    notes: 'Junger Stern aus Inzahlungnahme, Eingangscheck noch offen',
    historyNotes: ['Inzahlungnahme aus Flottenrücklauf'],
  },
  v5: {
    make: 'Mercedes-Benz',
    model: 'GLE 350 de 4MATIC',
    year: 2022,
    vin: 'W1N1671171A567890',
    color: 'Sodalithblau metallic',
    mileage: 35200,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 333,
    price: 72900,
    purchasePrice: 59800,
    imageUrl: mercedesMedia.gleExterior,
    notes: 'Hochvolt-Systemcheck und Ladeeinheit vor Freigabe prüfen',
  },
  v6: {
    make: 'Mercedes-Benz',
    model: 'EQE 350+',
    year: 2023,
    vin: 'W1KEV2DB8PF567890',
    color: 'Obsidian Black',
    mileage: 28400,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 292,
    price: 57900,
    purchasePrice: 48200,
    imageUrl: mercedesMedia.eqeExterior,
    notes: 'Burmester und MBUX Superscreen in der Anzeige prominent platzieren',
  },
  v7: {
    make: 'Mercedes-Benz',
    model: 'GLE 450 d 4MATIC',
    year: 2023,
    vin: 'W1N1671331A678901',
    color: 'Selenitgrau metallic',
    mileage: 58700,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 367,
    price: 78900,
    purchasePrice: 65200,
    imageUrl: mercedesMedia.gleStudio,
    notes: 'Luftfederung kalibrieren und Chromleiste rechts prüfen',
  },
  v8: {
    make: 'Mercedes-Benz',
    model: 'GLC 300 4MATIC',
    year: 2023,
    vin: 'W1N2546021F789012',
    color: 'Spektralblau metallic',
    mileage: 19800,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 258,
    price: 52900,
    purchasePrice: 44200,
    imageUrl: mercedesMedia.glcExterior,
    notes: 'AMG Line mit Night-Paket, sofort foto- und inseratsbereit',
  },
  v9: {
    make: 'Mercedes-Benz',
    model: 'EQE SUV 350 4MATIC',
    year: 2024,
    vin: 'W1N2946991D890123',
    color: 'Graphitgrau metallic',
    mileage: 12300,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 292,
    price: 71900,
    purchasePrice: 61800,
    imageUrl: mercedesMedia.eqeStudio,
    notes: 'Leasingrückläufer mit MBUX Hyperscreen, First Check offen',
  },
  v10: {
    make: 'Mercedes-Benz',
    model: 'GLA 220 d 4MATIC',
    year: 2022,
    vin: 'W1N2477121J012345',
    color: 'Manufaktur Opalithweiß',
    mileage: 42100,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 190,
    price: 37900,
    purchasePrice: 31100,
    imageUrl: mercedesMedia.glaExterior,
    notes: 'Service A und Reifencheck, danach Fotos für mobile.de',
  },
  v11: {
    make: 'Mercedes-Benz',
    model: 'CLA 250 e Shooting Brake',
    year: 2023,
    vin: 'W1K1186861N123456',
    color: 'Digitalweiß metallic',
    mileage: 31500,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 218,
    price: 36900,
    purchasePrice: 29800,
    imageUrl: mercedesMedia.claStudio,
    notes: 'Keramikpflege und Innenraum-Finish für AMG Line ausführen',
  },
  v12: {
    make: 'Mercedes-Benz',
    model: 'E 220 d T-Modell',
    year: 2024,
    vin: 'W1K2142031A234567',
    color: 'Verde Silber metallic',
    mileage: 15600,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 197,
    price: 63900,
    purchasePrice: 53800,
    imageUrl: mercedesMedia.eClassEstateStudio,
    notes: 'Digital Light, Burmester und Avantgarde Advanced Plus im Exposé ergänzen',
  },
  v13: {
    make: 'Mercedes-Benz',
    model: 'GLC 220 d 4MATIC Coupé',
    year: 2023,
    vin: 'W1N2539151F345678',
    color: 'Graphitgrau metallic',
    mileage: 40200,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 197,
    price: 48900,
    purchasePrice: 40600,
    imageUrl: mercedesMedia.glcStudio,
    notes: 'Bremsflüssigkeit wechseln und 4MATIC-Check dokumentieren',
  },
  v14: {
    make: 'Mercedes-Benz',
    model: 'A 250 e',
    year: 2023,
    vin: 'W1K1770841J234567',
    color: 'Kosmosschwarz metallic',
    mileage: 26800,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 218,
    price: 33900,
    purchasePrice: 27900,
    imageUrl: mercedesMedia.claStudio,
    notes: 'Innenreinigung, Ladekabel prüfen und AMG Styling fotografieren',
  },
  v15: {
    make: 'Mercedes-Benz',
    model: 'GLE 400 e 4MATIC',
    year: 2023,
    vin: 'W1N1671491A456789',
    color: 'Graphitgrau',
    mileage: 61200,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 381,
    price: 68400,
    purchasePrice: 54800,
    imageUrl: mercedesMedia.gleExterior,
    notes: 'Lackaufbereitung Heckklappe und Sensorik hinten prüfen',
  },
  v16: {
    make: 'Mercedes-Benz',
    model: 'GLA 200',
    year: 2023,
    vin: 'W1N2477131J567890',
    color: 'Mountaingrau metallic',
    mileage: 18900,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 163,
    price: 38900,
    purchasePrice: 32900,
    imageUrl: mercedesMedia.glaExterior,
    notes: 'Neu im Bestand, First Check und Preislabel noch offen',
    historyNotes: ['Junger Stern Zugang'],
  },
  v17: {
    make: 'Mercedes-Benz',
    model: 'EQE 300',
    year: 2023,
    vin: 'W1KEV2AA1PF678901',
    color: 'Hightechsilber metallic',
    mileage: 24100,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 245,
    price: 54900,
    purchasePrice: 44900,
    imageUrl: mercedesMedia.eqeExterior,
    notes: 'DC-Ladekabel, Wallbox-Hinweis und Fahrassistenzpaket kommunizieren',
  },
  v18: {
    make: 'Mercedes-Benz',
    model: 'C 300 e Limousine',
    year: 2022,
    vin: 'W1K2060531F890123',
    color: 'Polarweiß',
    mileage: 34400,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 313,
    price: 41900,
    purchasePrice: 33800,
    imageUrl: mercedesMedia.cClassStudio,
    notes: 'Bereits mit Kaufvertrag reserviert',
  },
  v19: {
    make: 'Mercedes-Benz',
    model: 'GLE 450 4MATIC',
    year: 2022,
    vin: 'W1N1671591A901234',
    color: 'Vulkangrau metallic',
    mileage: 32800,
    fuelType: 'Hybrid',
    transmission: 'Automatik',
    power: 381,
    price: 68900,
    purchasePrice: 57200,
    imageUrl: mercedesMedia.gleStudio,
    notes: 'Bremsen vorne erneuern und Night-Paket im Showroom hervorheben',
  },
  v20: {
    make: 'Mercedes-Benz',
    model: 'GLA 220 4MATIC',
    year: 2023,
    vin: 'W1N2477841J012346',
    color: 'Polarweiß',
    mileage: 17400,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 190,
    price: 44900,
    purchasePrice: 37900,
    imageUrl: mercedesMedia.glaExterior,
    notes: 'Winterräder und Rückfahrkamera im B2B-Angebot ergänzen',
  },
  v21: {
    make: 'Mercedes-Benz',
    model: 'GLC 300 e 4MATIC',
    year: 2023,
    vin: 'W1N2546201F345679',
    color: 'Selenitgrau metallic',
    mileage: 39200,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 313,
    price: 49800,
    purchasePrice: 40900,
    imageUrl: mercedesMedia.glcExterior,
    notes: 'HU-Termin vorbereiten und Ladezustand dokumentieren',
  },
  v22: {
    make: 'Mercedes-Benz',
    model: 'CLA 200 Coupé',
    year: 2022,
    vin: 'W1K1183121N456789',
    color: 'Manufaktur Patagonienrot metallic',
    mileage: 54800,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 163,
    price: 28900,
    purchasePrice: 22400,
    imageUrl: mercedesMedia.claStudio,
    notes: 'Inzahlungnahme von Stammkundin, Handoff an Service fehlt noch',
  },
}

export const mercedesInventoryVehicles: Vehicle[] = mockVehicles.map((vehicle) => {
  const override = inventoryVehicleOverrides[vehicle.id]
  if (!override) return vehicle

  return {
    ...vehicle,
    ...override,
    history: vehicle.history.map((entry, index) => ({
      ...entry,
      note: override.historyNotes?.[index] ?? entry.note,
    })),
  }
})

export const mercedesInventoryListings: Listing[] = [
  {
    id: 'l1',
    vehicleId: 'v3',
    title: 'Mercedes-Benz CLA 250 e Coupé AMG Line - Night-Paket, MBUX, Kamera',
    description: 'Sportlich gezeichnetes Mercedes-Benz CLA 250 e Coupé in Kosmosschwarz metallic mit AMG Line und Night-Paket. Das Plug-in-Hybrid-System mit 218 PS verbindet souveräne Fahrleistungen mit elektrischer Kurzstreckentauglichkeit. MBUX Navigation Premium, Rückfahrkamera, Sitzheizung vorne und LED High Performance sind bereits an Bord. Scheckheftgepflegt und aus erster Hand.',
    price: 32900,
    status: 'live',
    platform: ['mobile.de', 'autoscout24'],
    images: [
      mercedesMedia.claStudio,
      mercedesMedia.cClassStudio,
      mercedesMedia.claStudio,
      mercedesMedia.glaExterior,
    ],
    priceCategory: 'gut',
    marketPrice: 34200,
    aiGenerated: true,
    aiConfidence: 93,
    createdAt: '2026-02-20',
    updatedAt: '2026-03-05',
    views: 376,
    inquiries: 11,
  },
  {
    id: 'l2',
    vehicleId: 'v6',
    title: 'Mercedes-Benz EQE 350+ - Burmester, Superscreen, AIRMATIC',
    description: 'Vollelektrische Business-Limousine mit starker Ausstattung und effizientem 350+ Antrieb. Das Fahrzeug kombiniert Burmester 3D-Surround-Sound, MBUX Superscreen, AIRMATIC und umfangreiche Fahrassistenz für ein sehr hochwertiges Fahrerlebnis. Ladehistorie dokumentiert, sehr gepflegter Zustand, Junger Stern Garantie möglich.',
    price: 57900,
    status: 'live',
    platform: ['mobile.de'],
    images: [
      mercedesMedia.eqeExterior,
      mercedesMedia.eqeStudio,
      mercedesMedia.eqeExterior,
      mercedesMedia.eqeStudio,
    ],
    priceCategory: 'sehr_gut',
    marketPrice: 59800,
    aiGenerated: true,
    aiConfidence: 95,
    createdAt: '2026-02-21',
    updatedAt: '2026-03-06',
    views: 614,
    inquiries: 17,
  },
  {
    id: 'l3',
    vehicleId: 'v8',
    title: 'Mercedes-Benz GLC 300 4MATIC AMG Line - Panorama, 360°, Night-Paket',
    description: '',
    price: 52900,
    status: 'entwurf',
    platform: [],
    images: [
      mercedesMedia.glcExterior,
      mercedesMedia.glcStudio,
      mercedesMedia.glcExterior,
      mercedesMedia.gleExterior,
    ],
    priceCategory: 'zufriedenstellend',
    marketPrice: 51500,
    aiGenerated: false,
    aiConfidence: 0,
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
    views: 0,
    inquiries: 0,
  },
  {
    id: 'l4',
    vehicleId: 'v12',
    title: 'Mercedes-Benz E 220 d T-Modell Avantgarde - DIGITAL LIGHT, Burmester',
    description: 'Modernes Mercedes-Benz E 220 d T-Modell mit Avantgarde Line, DIGITAL LIGHT und hochwertigem Burmester-Soundsystem. Der effiziente Diesel mit 9G-TRONIC eignet sich ideal für Vielfahrer, während das neue MBUX und das große Kofferraumvolumen echten Langstreckenkomfort liefern. Gepflegter Erstbesitz, vollständige Servicehistorie vorhanden.',
    price: 63900,
    status: 'live',
    platform: ['mobile.de', 'autoscout24'],
    images: [
      mercedesMedia.eClassEstateStudio,
      mercedesMedia.cClassStudio,
      mercedesMedia.eClassEstateStudio,
      mercedesMedia.glcExterior,
    ],
    priceCategory: 'gut',
    marketPrice: 66200,
    aiGenerated: true,
    aiConfidence: 91,
    createdAt: '2026-02-14',
    updatedAt: '2026-03-04',
    views: 428,
    inquiries: 9,
  },
]

export const mercedesListingCreationVinMock = {
  vin: 'W1N2546021F789012',
  make: 'Mercedes-Benz',
  model: 'GLC 300 4MATIC AMG Line',
  year: '2023',
  mileage: '19.800',
  power: '258',
  displacement: '1.999',
  fuelType: 'benzin',
  transmission: 'automatik',
  color: 'Spektralblau Metallic',
  doors: '5',
  seats: '5',
  firstRegistration: '05.2023',
  hu: '05.2026',
  price: '52.900',
  serienausstattung: [
    'LED High Performance',
    'Klimaautomatik THERMATIC',
    'Rückfahrkamera',
    'Park-Assistent mit PARKTRONIC',
    'Sitzheizung vorne',
    'DAB+ Radio',
    'Bluetooth Freisprecheinrichtung',
    'Tempomat',
    'Lichtsensor',
    'Regensensor',
    'Isofix',
    'Start-Stop-System',
    'Bordcomputer',
    'Elektr. Fensterheber',
    'Elektr. Außenspiegel',
    'Zentralverriegelung',
    'ABS / ASR / ESP',
    'Spurhalte-Assistent',
    'Apple CarPlay',
    'Android Auto',
  ],
  sonderausstattung: [
    'AMG Line Exterieur',
    'Night-Paket',
    'Panorama-Schiebedach',
    'Burmester 3D-Surround-Soundsystem',
    'Head-up-Display',
    '360°-Kamera',
    'Memory-Paket',
    'AIRMATIC',
    'Fahrassistenz-Paket Plus',
    'Anhängerkupplung schwenkbar',
  ],
} as const

export const mercedesSeriesOptions = [
  'LED High Performance',
  'MULTIBEAM LED',
  'Tagfahrlicht',
  'Klimaautomatik THERMATIC',
  'Klimaanlage',
  'Rückfahrkamera',
  'Park-Assistent mit PARKTRONIC',
  'Einparkhilfe',
  'Sitzheizung vorne',
  'DAB+ Radio',
  'Bluetooth',
  'Apple CarPlay',
  'Android Auto',
  'Tempomat',
  'Lichtsensor',
  'Regensensor',
  'Isofix',
  'Start-Stop-System',
  'Bordcomputer',
  'Elektr. Fensterheber',
  'Elektr. Außenspiegel',
  'Zentralverriegelung',
  'ABS',
  'ASR',
  'ESP',
  'Airbags vorne',
  'Airbags seitlich',
  'Spurhalte-Assistent',
  'Totwinkel-Assistent',
  'Multifunktionslenkrad',
  'Ambientebeleuchtung',
] as const

export const mercedesExtraOptions = [
  'MBUX Navigation Premium',
  'MBUX Augmented Reality',
  'AMG Line',
  'Night-Paket',
  'Panorama-Schiebedach',
  'Head-up-Display',
  'Burmester 3D-Surround-Soundsystem',
  'AIRMATIC',
  'Memory-Paket',
  'Keyless-Go',
  'Fahrassistenz-Paket Plus',
  'Standheizung',
  'Anhängerkupplung',
  'Lederausstattung',
  '360°-Kamera',
  'DIGITAL LIGHT',
  'Massagesitze',
  'Belüftete Sitze',
  'DISTRONIC',
  'Ladepaket AC/DC',
] as const

export const mercedesListingCreationAiMock = {
  title: 'Mercedes-Benz GLC 300 4MATIC AMG Line - Night-Paket, Pano, Burmester',
  description: 'Gepflegter Mercedes-Benz GLC 300 4MATIC in Spektralblau metallic mit AMG Line und Night-Paket. Ausgestattet mit Panorama-Schiebedach, Burmester Soundsystem und 360°-Kamera. Der 258 PS starke Benziner bietet souveräne Fahrleistungen und hohen Langstreckenkomfort.\n\n✓ AMG Line\n✓ MBUX Navigation Premium\n✓ Panorama-Schiebedach\n✓ Burmester 3D-Surround-Sound\n✓ 360°-Kamera\n✓ Memory-Paket\n✓ Scheckheftgepflegt',
  improvedDescription: 'Dieser Mercedes-Benz GLC 300 4MATIC AMG Line verbindet elegantes SUV-Design mit hochwertiger Technik und überzeugendem Alltagskomfort. Die Spektralblau-Metallic-Lackierung harmoniert perfekt mit dem Night-Paket, während das Panorama-Schiebedach und das Burmester 3D-Surround-Soundsystem den Premium-Charakter zusätzlich unterstreichen.\n\nDer kultivierte 258-PS-Benziner arbeitet souverän mit der 9G-TRONIC zusammen und macht den GLC sowohl in der Stadt als auch auf langen Strecken zu einem sehr ausgewogenen Begleiter.\n\n✓ AMG Line mit Night-Paket\n✓ Panorama-Schiebedach elektrisch\n✓ Burmester 3D-Surround-Soundsystem\n✓ 360°-Kamera und Park-Assistent\n✓ Memory-Paket und Sitzheizung vorne\n✓ 1 Vorbesitzer - lückenlos scheckheftgepflegt',
  kycScore: 78,
  improvedKycScore: 97,
  confidence: 94,
  priceAnalysis: {
    marketPrice: 54800,
    suggestion: 52900,
    category: 'gut' as const,
    thresholds: [
      { label: 'Sehr gut', max: 49900 },
      { label: 'Gut', max: 53500 },
      { label: 'Zufriedenstellend', max: 55900 },
      { label: 'Erhöht', max: 58900 },
    ],
  },
} as const

export const mercedesListingCreationImageSlots = [
  {
    id: 0,
    label: 'Frontansicht',
    original: mercedesMedia.glcExterior,
    cutout: mercedesMedia.glcStudio,
    background: mercedesMedia.gleExterior,
    quality: mercedesMedia.glcExterior,
  },
  {
    id: 1,
    label: 'Seitenansicht',
    original: mercedesMedia.gleExterior,
    cutout: mercedesMedia.gleStudio,
    background: mercedesMedia.glcExterior,
    quality: mercedesMedia.gleExterior,
  },
  {
    id: 2,
    label: 'Detailansicht',
    original: mercedesMedia.cClassStudio,
    cutout: mercedesMedia.eqeStudio,
    background: mercedesMedia.eqeExterior,
    quality: mercedesMedia.eqeExterior,
  },
] as const
