import type {
  Vehicle, Callback, Advisor, Listing, Conversation,
  KYCSubmission, DashboardStats, ActivityEntry, VehicleListRowLegacy,
  AccountingDocument, VehicleAccountingCase, AccountingExportBatch,
} from './types'

// ============================================
// Fahrzeuge
// ============================================

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    make: 'BMW',
    model: '320d Touring',
    year: 2022,
    vin: 'WBAPH5C55BA123456',
    licensePlate: 'S-WH 1234',
    color: 'Mineralweiß',
    mileage: 45200,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 190,
    price: 34900,
    purchasePrice: 28500,
    status: 'werkstatt',
    location: 'Werkstatt',
    intakeDate: '2026-02-25',
    deadline: '2026-03-07',
    imageUrl: 'https://images.unsplash.com/photo-1592665252707-5fa7e3ceed02?w=800&h=500&fit=crop',
    notes: 'Bremsen hinten erneuern, Inspektion fällig',
    history: [
      { id: 'h1', date: '2026-02-25', action: 'Eingang', user: 'Thomas M.', note: 'Ankauf von Privat' },
      { id: 'h2', date: '2026-02-26', action: 'Inspektion', user: 'Michael S.', note: 'Bremsen hinten 2mm, Service fällig' },
      { id: 'h3', date: '2026-02-27', action: 'Werkstatt', user: 'Michael S.' },
    ],
  },
  {
    id: 'v2',
    make: 'Mercedes-Benz',
    model: 'C 200 Limousine',
    year: 2023,
    vin: 'WDD2050001A234567',
    licensePlate: 'S-WH 2345',
    color: 'Obsidianschwarz',
    mileage: 22100,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 204,
    price: 38500,
    purchasePrice: 31200,
    status: 'aufbereitung',
    location: 'Werkstatt',
    intakeDate: '2026-02-22',
    deadline: '2026-03-04',
    imageUrl: 'https://images.unsplash.com/photo-1610469167200-3e7b77ddd398?w=800&h=500&fit=crop',
    notes: 'Aufbereitung: Polieren, Innenreinigung',
    history: [
      { id: 'h4', date: '2026-02-22', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h5', date: '2026-02-23', action: 'Inspektion', user: 'Michael S.', note: 'Keine Mängel' },
      { id: 'h6', date: '2026-02-24', action: 'Aufbereitung', user: 'Lisa K.' },
    ],
  },
  {
    id: 'v3',
    make: 'Audi',
    model: 'A4 Avant 40 TDI',
    year: 2021,
    vin: 'WAUZZZ8V3LA345678',
    licensePlate: 'S-WH 3456',
    color: 'Navarrablau',
    mileage: 67800,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 204,
    price: 29900,
    purchasePrice: 23800,
    status: 'verkaufsbereit',
    location: 'Showroom',
    intakeDate: '2026-02-15',
    deadline: '2026-02-25',
    imageUrl: 'https://images.unsplash.com/photo-1587149753552-6d8ed3947365?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h7', date: '2026-02-15', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h8', date: '2026-02-16', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h9', date: '2026-02-18', action: 'Werkstatt', user: 'Michael S.', note: 'Ölwechsel' },
      { id: 'h10', date: '2026-02-19', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h11', date: '2026-02-20', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v4',
    make: 'VW',
    model: 'Golf 8 GTI',
    year: 2023,
    vin: 'WVWZZZ1KZPW456789',
    licensePlate: 'S-WH 4567',
    color: 'Tornadorot',
    mileage: 18500,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 245,
    price: 35900,
    purchasePrice: 29400,
    status: 'eingang',
    location: 'Hof A',
    intakeDate: '2026-03-03',
    deadline: '2026-03-13',
    imageUrl: 'https://images.unsplash.com/photo-1560282105-222992ffb774?w=800&h=500&fit=crop',
    notes: 'Tauschgeschäft, Kunde bringt A3 mit',
    history: [
      { id: 'h12', date: '2026-03-03', action: 'Eingang', user: 'Thomas M.', note: 'Tauschgeschäft' },
    ],
  },
  {
    id: 'v5',
    make: 'Porsche',
    model: 'Cayenne E-Hybrid',
    year: 2022,
    vin: 'WP1AG2AY3PDA56789',
    licensePlate: 'S-WH 5678',
    color: 'Kreide',
    mileage: 35200,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 462,
    price: 72900,
    purchasePrice: 59800,
    status: 'inspektion',
    location: 'Werkstatt',
    intakeDate: '2026-03-02',
    deadline: '2026-03-12',
    imageUrl: 'https://images.unsplash.com/photo-1672169538777-fb3211046a03?w=800&h=500&fit=crop',
    notes: 'Hochpreisiges Fahrzeug - sorgfältige Inspektion',
    history: [
      { id: 'h13', date: '2026-03-02', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h14', date: '2026-03-03', action: 'Inspektion', user: 'Michael S.' },
    ],
  },
  {
    id: 'v6',
    make: 'Tesla',
    model: 'Model 3 Long Range',
    year: 2023,
    vin: '5YJ3E1EA3PF567890',
    licensePlate: 'S-WH 6789',
    color: 'Pearl White',
    mileage: 28400,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 366,
    price: 37900,
    purchasePrice: 31500,
    status: 'verkaufsbereit',
    location: 'Showroom',
    intakeDate: '2026-02-18',
    deadline: '2026-02-28',
    imageUrl: 'https://images.unsplash.com/photo-1561580125-028ee3bd62eb?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h15', date: '2026-02-18', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h16', date: '2026-02-19', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h17', date: '2026-02-20', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h18', date: '2026-02-21', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v7',
    make: 'BMW',
    model: 'X3 xDrive30d',
    year: 2021,
    vin: 'WBAUJ110XL7678901',
    licensePlate: 'S-WH 7890',
    color: 'Phytonicblau',
    mileage: 58700,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 286,
    price: 39900,
    purchasePrice: 32600,
    status: 'werkstatt',
    location: 'Werkstatt',
    intakeDate: '2026-02-20',
    deadline: '2026-03-02',
    imageUrl: 'https://images.unsplash.com/photo-1752883749566-e1cbac1bf657?w=800&h=500&fit=crop',
    notes: 'Steuerkette klappern, muss getauscht werden',
    history: [
      { id: 'h19', date: '2026-02-20', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h20', date: '2026-02-21', action: 'Inspektion', user: 'Michael S.', note: 'Steuerkette auffällig' },
      { id: 'h21', date: '2026-02-22', action: 'Werkstatt', user: 'Michael S.' },
    ],
  },
  {
    id: 'v8',
    make: 'Mercedes-Benz',
    model: 'GLC 300 4MATIC',
    year: 2023,
    vin: 'WDC2539001F789012',
    licensePlate: 'S-WH 8901',
    color: 'Selenitgrau',
    mileage: 19800,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 258,
    price: 52900,
    purchasePrice: 44200,
    status: 'verkaufsbereit',
    location: 'Hof B',
    intakeDate: '2026-02-12',
    deadline: '2026-02-22',
    imageUrl: 'https://images.unsplash.com/photo-1597725213905-7fb3f069ce18?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h22', date: '2026-02-12', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h23', date: '2026-02-13', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h24', date: '2026-02-14', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h25', date: '2026-02-15', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v9',
    make: 'Audi',
    model: 'e-tron GT',
    year: 2023,
    vin: 'WAUZZZ4M1PD890123',
    licensePlate: 'S-WH 9012',
    color: 'Daytona Grau',
    mileage: 12300,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 476,
    price: 79900,
    purchasePrice: 67500,
    status: 'eingang',
    location: 'Hof A',
    intakeDate: '2026-03-04',
    deadline: '2026-03-14',
    imageUrl: 'https://images.unsplash.com/photo-1683728960304-4e0c299359bf?w=800&h=500&fit=crop',
    notes: 'Neuwertig, Leasingrückläufer',
    history: [
      { id: 'h26', date: '2026-03-04', action: 'Eingang', user: 'Thomas M.', note: 'Leasingrückläufer' },
    ],
  },
  {
    id: 'v10',
    make: 'VW',
    model: 'Tiguan 2.0 TDI',
    year: 2022,
    vin: 'WVGZZZ5NZPW012345',
    licensePlate: 'S-WH 0123',
    color: 'Oryx Weiß',
    mileage: 42100,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 150,
    price: 28900,
    purchasePrice: 23100,
    status: 'werkstatt',
    location: 'Werkstatt',
    intakeDate: '2026-02-26',
    deadline: '2026-03-08',
    imageUrl: 'https://images.unsplash.com/photo-1655286517582-08a1483aa0fd?w=800&h=500&fit=crop',
    notes: 'Service, neue Reifen',
    history: [
      { id: 'h27', date: '2026-02-26', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h28', date: '2026-02-27', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h29', date: '2026-02-28', action: 'Werkstatt', user: 'Michael S.', note: 'Service + Reifen' },
    ],
  },
  {
    id: 'v11',
    make: 'Skoda',
    model: 'Octavia Combi RS',
    year: 2023,
    vin: 'TMBAH7NP1P0123456',
    licensePlate: 'S-WH 1122',
    color: 'Stahlgrau',
    mileage: 31500,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 245,
    price: 32500,
    purchasePrice: 26800,
    status: 'aufbereitung',
    location: 'Werkstatt',
    intakeDate: '2026-02-28',
    deadline: '2026-03-10',
    imageUrl: 'https://images.unsplash.com/photo-1528820846917-a476472ee6b3?w=800&h=500&fit=crop',
    notes: 'Polieren, Keramikversiegelung',
    history: [
      { id: 'h30', date: '2026-02-28', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h31', date: '2026-03-01', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h32', date: '2026-03-02', action: 'Werkstatt', user: 'Michael S.' },
      { id: 'h33', date: '2026-03-03', action: 'Aufbereitung', user: 'Lisa K.' },
    ],
  },
  {
    id: 'v12',
    make: 'BMW',
    model: 'iX xDrive50',
    year: 2023,
    vin: 'WBYMA810XP7234567',
    licensePlate: 'S-WH 3344',
    color: 'Mineralweiß',
    mileage: 15600,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 523,
    price: 69900,
    purchasePrice: 58500,
    status: 'verkaufsbereit',
    location: 'Showroom',
    intakeDate: '2026-02-10',
    deadline: '2026-02-20',
    imageUrl: 'https://images.unsplash.com/photo-1677517859847-0e750bfd13a9?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h34', date: '2026-02-10', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h35', date: '2026-02-11', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h36', date: '2026-02-12', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h37', date: '2026-02-13', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v13',
    make: 'Audi',
    model: 'Q5 40 TFSI quattro',
    year: 2022,
    vin: 'WAUZZZFY6N1234567',
    licensePlate: 'S-WH 4455',
    color: 'Mythosschwarz',
    mileage: 40200,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 204,
    price: 42900,
    purchasePrice: 35600,
    status: 'inspektion',
    location: 'Werkstatt',
    intakeDate: '2026-03-01',
    deadline: '2026-03-11',
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=500&fit=crop',
    notes: 'Inspektion + Bremsflüssigkeit wechseln',
    history: [
      { id: 'h38', date: '2026-03-01', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h39', date: '2026-03-02', action: 'Inspektion', user: 'Michael S.', note: 'Service fällig' },
    ],
  },
  {
    id: 'v14',
    make: 'Mercedes-Benz',
    model: 'A 250 e',
    year: 2023,
    vin: 'W1K1770841J234567',
    licensePlate: 'S-WH 5566',
    color: 'Kosmosschwarz',
    mileage: 26800,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 218,
    price: 33900,
    purchasePrice: 27900,
    status: 'aufbereitung',
    location: 'Werkstatt',
    intakeDate: '2026-02-27',
    deadline: '2026-03-09',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop',
    notes: 'Innenreinigung und Felgenaufbereitung',
    history: [
      { id: 'h40', date: '2026-02-27', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h41', date: '2026-02-28', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h42', date: '2026-03-01', action: 'Aufbereitung', user: 'Lisa K.' },
    ],
  },
  {
    id: 'v15',
    make: 'Volvo',
    model: 'XC60 B5 AWD',
    year: 2021,
    vin: 'YV1UZK5VCM1456789',
    licensePlate: 'S-WH 6677',
    color: 'Thunder Grey',
    mileage: 61200,
    fuelType: 'Hybrid',
    transmission: 'Automatik',
    power: 250,
    price: 36400,
    purchasePrice: 29800,
    status: 'werkstatt',
    location: 'Werkstatt',
    intakeDate: '2026-02-24',
    deadline: '2026-03-06',
    imageUrl: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=800&h=500&fit=crop',
    notes: 'Stoßdämpfer hinten prüfen',
    history: [
      { id: 'h43', date: '2026-02-24', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h44', date: '2026-02-25', action: 'Inspektion', user: 'Michael S.', note: 'Dämpfer hinten feucht' },
      { id: 'h45', date: '2026-02-26', action: 'Werkstatt', user: 'Michael S.' },
    ],
  },
  {
    id: 'v16',
    make: 'Cupra',
    model: 'Formentor VZ',
    year: 2023,
    vin: 'VSSZZZKM3PR567890',
    licensePlate: 'S-WH 7788',
    color: 'Magnetic Grau',
    mileage: 18900,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 310,
    price: 38900,
    purchasePrice: 32900,
    status: 'eingang',
    location: 'Hof A',
    intakeDate: '2026-03-04',
    deadline: '2026-03-14',
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&h=500&fit=crop',
    notes: 'Neu im Bestand, First Check offen',
    history: [
      { id: 'h46', date: '2026-03-04', action: 'Eingang', user: 'Thomas M.', note: 'Leasingrückläufer' },
    ],
  },
  {
    id: 'v17',
    make: 'Renault',
    model: 'Zoe R135',
    year: 2022,
    vin: 'VF1AG000006789012',
    licensePlate: 'S-WH 8899',
    color: 'Aqua Blau',
    mileage: 24100,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 136,
    price: 18900,
    purchasePrice: 14900,
    status: 'verkaufsbereit',
    location: 'Hof B',
    intakeDate: '2026-02-16',
    deadline: '2026-02-26',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h47', date: '2026-02-16', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h48', date: '2026-02-17', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h49', date: '2026-02-18', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h50', date: '2026-02-19', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v18',
    make: 'Peugeot',
    model: '3008 GT BlueHDi',
    year: 2021,
    vin: 'VF3MRYHZRMS890123',
    licensePlate: 'S-WH 9900',
    color: 'Perlmutt Weiß',
    mileage: 73400,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    power: 177,
    price: 24900,
    purchasePrice: 19800,
    status: 'verkauft',
    location: 'Showroom',
    intakeDate: '2026-02-05',
    deadline: '2026-02-15',
    imageUrl: 'https://images.unsplash.com/photo-1532581140115-3e355d1ed1de?w=800&h=500&fit=crop',
    notes: 'Bereits mit Kaufvertrag reserviert',
    history: [
      { id: 'h51', date: '2026-02-05', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h52', date: '2026-02-06', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h53', date: '2026-02-08', action: 'Verkaufsbereit', user: 'Thomas M.' },
      { id: 'h54', date: '2026-02-09', action: 'Verkauft', user: 'Sarah W.' },
    ],
  },
  {
    id: 'v19',
    make: 'Porsche',
    model: 'Macan S',
    year: 2022,
    vin: 'WP1ZZZ95ZNL901234',
    licensePlate: 'S-WH 1010',
    color: 'Vulkangrau',
    mileage: 32800,
    fuelType: 'Benzin',
    transmission: 'Automatik',
    power: 380,
    price: 68900,
    purchasePrice: 57200,
    status: 'werkstatt',
    location: 'Werkstatt',
    intakeDate: '2026-03-03',
    deadline: '2026-03-13',
    imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&h=500&fit=crop',
    notes: 'Bremsen vorne erneuern',
    history: [
      { id: 'h55', date: '2026-03-03', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h56', date: '2026-03-04', action: 'Inspektion', user: 'Michael S.', note: 'Scheiben vorne 2mm' },
      { id: 'h57', date: '2026-03-04', action: 'Werkstatt', user: 'Michael S.' },
    ],
  },
  {
    id: 'v20',
    make: 'Hyundai',
    model: 'IONIQ 5 AWD',
    year: 2023,
    vin: 'KMHKR81APPU012345',
    licensePlate: 'S-WH 2020',
    color: 'Digital Teal',
    mileage: 17400,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    power: 306,
    price: 44900,
    purchasePrice: 37900,
    status: 'verkaufsbereit',
    location: 'Showroom',
    intakeDate: '2026-02-14',
    deadline: '2026-02-24',
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&h=500&fit=crop',
    notes: '',
    history: [
      { id: 'h58', date: '2026-02-14', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h59', date: '2026-02-15', action: 'Inspektion', user: 'Michael S.' },
      { id: 'h60', date: '2026-02-16', action: 'Aufbereitung', user: 'Lisa K.' },
      { id: 'h61', date: '2026-02-17', action: 'Verkaufsbereit', user: 'Thomas M.' },
    ],
  },
  {
    id: 'v21',
    make: 'Kia',
    model: 'Sorento 1.6 T-GDI PHEV',
    year: 2022,
    vin: 'KNARH81BPNA345678',
    licensePlate: 'S-WH 2121',
    color: 'Graphit',
    mileage: 39200,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    power: 265,
    price: 41800,
    purchasePrice: 34900,
    status: 'inspektion',
    location: 'Werkstatt',
    intakeDate: '2026-03-02',
    deadline: '2026-03-12',
    imageUrl: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&h=500&fit=crop',
    notes: 'HU-Termin vorbereiten',
    history: [
      { id: 'h62', date: '2026-03-02', action: 'Eingang', user: 'Thomas M.' },
      { id: 'h63', date: '2026-03-03', action: 'Inspektion', user: 'Michael S.' },
    ],
  },
  {
    id: 'v22',
    make: 'BMW',
    model: '118i',
    year: 2021,
    vin: 'WBA7K11090G456789',
    licensePlate: 'S-WH 2222',
    color: 'Alpinweiß',
    mileage: 54800,
    fuelType: 'Benzin',
    transmission: 'Schaltung',
    power: 136,
    price: 21900,
    purchasePrice: 17400,
    status: 'eingang',
    location: 'Hof B',
    intakeDate: '2026-03-04',
    deadline: '2026-03-14',
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=800&h=500&fit=crop',
    notes: 'Ankauf von Stammkunde',
    history: [
      { id: 'h64', date: '2026-03-04', action: 'Eingang', user: 'Thomas M.', note: 'Ankauf privat' },
    ],
  },
]

export const mockVehicleListRowsLegacy: VehicleListRowLegacy[] = [
  {
    id: 'legacy-v1',
    vehicleId: 'v1',
    autoId: '242925',
    catalogNumber: '315',
    kNumber: 'K-071',
    lotNumber: '71',
    minimumPrice: 8800,
    currentBid: 8500,
    auctionStatus: 'verkauft',
    imagesAvailable: true,
    auctionDate: '2026-02-04',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: true,
    huValidUntil: '2026-11-01',
    damageNote: 'Seitenschaden',
    lastAuction: 'Letzte Auktion',
    listingUrl: 'https://lahfauto.de/inserat/v1',
    contractTextUrl: 'https://lahfauto.de/vertrag/v1',
    rowLocked: true,
  },
  {
    id: 'legacy-v2',
    vehicleId: 'v2',
    autoId: '243494',
    catalogNumber: '315',
    kNumber: 'K-008',
    lotNumber: '8',
    minimumPrice: 14700,
    currentBid: 14200,
    auctionStatus: 'aktiv',
    imagesAvailable: true,
    auctionDate: '2026-02-14',
    docsCoc: true,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2027-10-01',
    damageNote: 'Heckschaden, Nachlackierungen links',
    lastAuction: 'Auktion 14.02.2026',
    listingUrl: 'https://lahfauto.de/inserat/v2',
    contractTextUrl: 'https://lahfauto.de/vertrag/v2',
  },
  {
    id: 'legacy-v3',
    vehicleId: 'v3',
    autoId: '243290',
    catalogNumber: '315',
    kNumber: 'K-060',
    lotNumber: '60',
    minimumPrice: 35400,
    currentBid: 34700,
    auctionStatus: 'verkauft',
    imagesAvailable: false,
    auctionDate: '2026-01-08',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2027-06-01',
    damageNote: 'Seitenschaden rechts, leichter Kratzer VL',
    lastAuction: 'Auktion 08.01.2026',
    listingUrl: 'https://lahfauto.de/inserat/v3',
    contractTextUrl: 'https://lahfauto.de/vertrag/v3',
    rowLocked: true,
  },
  {
    id: 'legacy-v4',
    vehicleId: 'v4',
    autoId: '250110',
    catalogNumber: '315',
    kNumber: 'K-020',
    lotNumber: '20',
    minimumPrice: 10900,
    currentBid: 10700,
    auctionStatus: 'verkauft',
    imagesAvailable: false,
    auctionDate: '2026-02-04',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2026-12-01',
    damageNote: 'Optische Mängel',
    lastAuction: 'Auktion 04.02.2026',
    listingUrl: 'https://lahfauto.de/inserat/v4',
    contractTextUrl: 'https://lahfauto.de/vertrag/v4',
    rowLocked: true,
  },
  {
    id: 'legacy-v5',
    vehicleId: 'v5',
    autoId: '242568',
    catalogNumber: '315',
    kNumber: 'K-078',
    lotNumber: '78',
    minimumPrice: 12700,
    currentBid: 0,
    auctionStatus: 'aktiv',
    imagesAvailable: true,
    auctionDate: '2026-01-11',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2027-07-01',
    damageNote: 'Unfall vorn rechts',
    lastAuction: 'Auktion 11.01.2026',
    listingUrl: 'https://lahfauto.de/inserat/v5',
    contractTextUrl: 'https://lahfauto.de/vertrag/v5',
  },
  {
    id: 'legacy-v6',
    vehicleId: 'v6',
    autoId: '250017',
    catalogNumber: '315',
    kNumber: 'K-003',
    lotNumber: '3',
    minimumPrice: 7000,
    currentBid: 6900,
    auctionStatus: 'verkauft',
    imagesAvailable: false,
    auctionDate: '2026-02-04',
    docsCoc: false,
    docsServiceHistory: false,
    docsSpareKey: false,
    huValidUntil: '2026-06-01',
    damageNote: 'Seitenschaden',
    lastAuction: 'Auktion 04.02.2026',
    listingUrl: 'https://lahfauto.de/inserat/v6',
    contractTextUrl: 'https://lahfauto.de/vertrag/v6',
    rowLocked: true,
  },
  {
    id: 'legacy-v7',
    vehicleId: 'v7',
    autoId: '243370',
    catalogNumber: '315',
    kNumber: 'K-052',
    lotNumber: '52',
    minimumPrice: 12600,
    currentBid: 11950,
    auctionStatus: 'reserviert',
    imagesAvailable: true,
    auctionDate: '2026-01-04',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2026-08-01',
    damageNote: 'Seitenschaden links, VL Achse prüfen',
    lastAuction: 'Auktion 04.01.2026',
    listingUrl: 'https://lahfauto.de/inserat/v7',
    contractTextUrl: 'https://lahfauto.de/vertrag/v7',
  },
  {
    id: 'legacy-v8',
    vehicleId: 'v8',
    autoId: '243915',
    catalogNumber: '318',
    kNumber: 'K-011',
    lotNumber: '11',
    minimumPrice: 19400,
    currentBid: 18800,
    auctionStatus: 'aktiv',
    imagesAvailable: true,
    auctionDate: '2026-03-01',
    docsCoc: true,
    docsServiceHistory: true,
    docsSpareKey: true,
    huValidUntil: '2028-01-01',
    damageNote: 'Keine sichtbaren Schäden',
    lastAuction: 'Auktion 01.03.2026',
    listingUrl: 'https://lahfauto.de/inserat/v8',
    contractTextUrl: 'https://lahfauto.de/vertrag/v8',
  },
  {
    id: 'legacy-v9',
    vehicleId: 'v9',
    autoId: '244011',
    catalogNumber: '321',
    kNumber: 'K-102',
    lotNumber: '102',
    minimumPrice: 52900,
    currentBid: 51100,
    auctionStatus: 'aktiv',
    imagesAvailable: true,
    auctionDate: '2026-03-04',
    docsCoc: true,
    docsServiceHistory: false,
    docsSpareKey: true,
    huValidUntil: '2027-05-01',
    damageNote: 'Leichter Parkschaden Stoßfänger hinten',
    lastAuction: 'Auktion 04.03.2026',
    listingUrl: 'https://lahfauto.de/inserat/v9',
    contractTextUrl: 'https://lahfauto.de/vertrag/v9',
  },
  {
    id: 'legacy-v10',
    vehicleId: 'v10',
    autoId: '244020',
    catalogNumber: '322',
    kNumber: 'K-039',
    lotNumber: '39',
    minimumPrice: 17600,
    currentBid: 16800,
    auctionStatus: 'reserviert',
    imagesAvailable: false,
    auctionDate: '2026-02-27',
    docsCoc: false,
    docsServiceHistory: true,
    docsSpareKey: true,
    huValidUntil: '2027-02-01',
    damageNote: 'Kleine Delle HR, sonst gepflegt',
    lastAuction: 'Auktion 27.02.2026',
    listingUrl: 'https://lahfauto.de/inserat/v10',
    contractTextUrl: 'https://lahfauto.de/vertrag/v10',
  },
  {
    id: 'legacy-v11',
    vehicleId: 'v11',
    autoId: '244103',
    catalogNumber: '325',
    kNumber: 'K-087',
    lotNumber: '87',
    minimumPrice: 22100,
    currentBid: 21800,
    auctionStatus: 'aktiv',
    imagesAvailable: true,
    auctionDate: '2026-03-03',
    docsCoc: true,
    docsServiceHistory: true,
    docsSpareKey: false,
    huValidUntil: '2026-09-01',
    damageNote: 'Felge vorne rechts mit Bordsteinschaden',
    lastAuction: 'Auktion 03.03.2026',
    listingUrl: 'https://lahfauto.de/inserat/v11',
    contractTextUrl: 'https://lahfauto.de/vertrag/v11',
  },
  {
    id: 'legacy-v12',
    vehicleId: 'v12',
    autoId: '244180',
    catalogNumber: '329',
    kNumber: 'K-118',
    lotNumber: '118',
    minimumPrice: 47500,
    currentBid: 46800,
    auctionStatus: 'verkauft',
    imagesAvailable: true,
    auctionDate: '2026-02-20',
    docsCoc: true,
    docsServiceHistory: true,
    docsSpareKey: true,
    huValidUntil: '2027-12-01',
    damageNote: 'Keine Mängel',
    lastAuction: 'Auktion 20.02.2026',
    listingUrl: 'https://lahfauto.de/inserat/v12',
    contractTextUrl: 'https://lahfauto.de/vertrag/v12',
    rowLocked: true,
  },
]

// ============================================
// Callbacks
// ============================================

export const mockAdvisors: Advisor[] = [
  { id: 'a1', name: 'Thomas Müller', avatar: '', role: 'Verkaufsberater', openCallbacks: 3, completedToday: 5, overdueCallbacks: 1 },
  { id: 'a2', name: 'Sarah Weber', avatar: '', role: 'Verkaufsberaterin', openCallbacks: 2, completedToday: 7, overdueCallbacks: 0 },
  { id: 'a3', name: 'Michael Schmidt', avatar: '', role: 'Serviceberater', openCallbacks: 4, completedToday: 3, overdueCallbacks: 2 },
  { id: 'a4', name: 'Lisa Kramer', avatar: '', role: 'Verkaufsberaterin', openCallbacks: 1, completedToday: 6, overdueCallbacks: 0 },
]

export const mockCallbacks: Callback[] = [
  {
    id: 'cb1',
    customerName: 'Hans Gruber',
    customerPhone: '+49 711 1234567',
    reason: 'Probefahrt BMW 320d anfragen',
    notes: 'Kunde hat online angefragt, möchte morgen vorbeikommen',
    assignedAdvisor: 'Thomas Müller',
    status: 'offen',
    priority: 'hoch',
    createdAt: '2026-03-04T09:15:00',
    updatedAt: '2026-03-04T09:15:00',
    slaDeadline: '2026-03-04T11:15:00',
  },
  {
    id: 'cb2',
    customerName: 'Maria Schneider',
    customerPhone: '+49 711 2345678',
    reason: 'Frage zur Finanzierung Mercedes C200',
    notes: 'Kundin möchte Leasingrate wissen',
    assignedAdvisor: 'Sarah Weber',
    status: 'in_bearbeitung',
    priority: 'mittel',
    createdAt: '2026-03-04T08:30:00',
    updatedAt: '2026-03-04T09:45:00',
    slaDeadline: '2026-03-04T10:30:00',
  },
  {
    id: 'cb3',
    customerName: 'Peter Wagner',
    customerPhone: '+49 711 3456789',
    reason: 'Reklamation Ölwechsel',
    notes: 'Kunde behauptet Ölverlust nach Service',
    assignedAdvisor: 'Michael Schmidt',
    status: 'ueberfaellig',
    priority: 'dringend',
    createdAt: '2026-03-03T14:00:00',
    updatedAt: '2026-03-03T14:00:00',
    slaDeadline: '2026-03-03T16:00:00',
  },
  {
    id: 'cb4',
    customerName: 'Anna Hoffmann',
    customerPhone: '+49 711 4567890',
    reason: 'Fahrzeugbewertung für Inzahlungnahme',
    notes: 'Golf 7, 2019, ca. 80.000km',
    assignedAdvisor: 'Thomas Müller',
    status: 'offen',
    priority: 'niedrig',
    createdAt: '2026-03-04T10:00:00',
    updatedAt: '2026-03-04T10:00:00',
    slaDeadline: '2026-03-04T12:00:00',
  },
  {
    id: 'cb5',
    customerName: 'Klaus Becker',
    customerPhone: '+49 711 5678901',
    reason: 'Abholtermin vereinbaren',
    notes: 'Tesla Model 3 ist bereit, Kunde informieren',
    assignedAdvisor: 'Lisa Kramer',
    status: 'erledigt',
    priority: 'mittel',
    createdAt: '2026-03-04T07:45:00',
    updatedAt: '2026-03-04T08:20:00',
    completedAt: '2026-03-04T08:20:00',
    completionNotes: 'Kunde kommt Freitag 14 Uhr',
    slaDeadline: '2026-03-04T09:45:00',
  },
  {
    id: 'cb6',
    customerName: 'Stefanie Klein',
    customerPhone: '+49 711 6789012',
    reason: 'Garantiefrage Porsche Cayenne',
    notes: 'Herstellergarantie vs. Händlergarantie',
    assignedAdvisor: 'Michael Schmidt',
    status: 'ueberfaellig',
    priority: 'hoch',
    createdAt: '2026-03-03T16:30:00',
    updatedAt: '2026-03-03T16:30:00',
    slaDeadline: '2026-03-03T18:30:00',
  },
  {
    id: 'cb7',
    customerName: 'Jürgen Fischer',
    customerPhone: '+49 711 7890123',
    reason: 'Reifenwechsel Termin',
    notes: 'Winterreifen auf Sommerreifen, eigene Reifen',
    assignedAdvisor: 'Michael Schmidt',
    status: 'offen',
    priority: 'niedrig',
    createdAt: '2026-03-04T10:30:00',
    updatedAt: '2026-03-04T10:30:00',
    slaDeadline: '2026-03-04T12:30:00',
  },
  {
    id: 'cb8',
    customerName: 'Christina Braun',
    customerPhone: '+49 711 8901234',
    reason: 'Preisverhandlung Audi A4',
    notes: 'Kundin möchte Preis nachverhandeln, hat Angebot von Konkurrenz',
    assignedAdvisor: 'Thomas Müller',
    status: 'offen',
    priority: 'hoch',
    createdAt: '2026-03-04T11:00:00',
    updatedAt: '2026-03-04T11:00:00',
    slaDeadline: '2026-03-04T13:00:00',
  },
  {
    id: 'cb9',
    customerName: 'Robert Meier',
    customerPhone: '+49 711 9012345',
    reason: 'Nachfrage Zulassung',
    notes: 'Wann ist sein neues Fahrzeug zugelassen?',
    assignedAdvisor: 'Sarah Weber',
    status: 'erledigt',
    priority: 'mittel',
    createdAt: '2026-03-04T08:00:00',
    updatedAt: '2026-03-04T09:00:00',
    completedAt: '2026-03-04T09:00:00',
    completionNotes: 'Zulassung kommt morgen, Kunde informiert',
    slaDeadline: '2026-03-04T10:00:00',
  },
]

// ============================================
// Inserate
// ============================================

export const mockListings: Listing[] = [
  {
    id: 'l1',
    vehicleId: 'v3',
    title: 'Audi A4 Avant 40 TDI quattro S-tronic - Navi, LED, Sportpaket',
    description: 'Gepflegter Audi A4 Avant in Navarrablau metallic mit umfangreicher Ausstattung. S line Sportpaket, MMI Navigation plus, LED-Scheinwerfer, Einparkhilfe vorne und hinten, Sitzheizung, 3-Zonen Klimaautomatik. Scheckheftgepflegt mit lückenloser Servicehistorie beim Audi Partner. Nichtraucherfahrzeug.',
    price: 29900,
    status: 'live',
    platform: ['mobile.de', 'autoscout24'],
    images: [],
    priceCategory: 'gut',
    marketPrice: 31200,
    aiGenerated: true,
    aiConfidence: 92,
    createdAt: '2026-02-20',
    updatedAt: '2026-02-20',
    views: 342,
    inquiries: 8,
  },
  {
    id: 'l2',
    vehicleId: 'v6',
    title: 'Tesla Model 3 Long Range AWD - Autopilot, Premium, Top Zustand',
    description: 'Tesla Model 3 Long Range in Pearl White mit Premium-Innenausstattung. Autopilot, 18" Aero-Felgen, Glasdach, Premium-Soundsystem. Reichweite ca. 580km WLTP. Akku-Gesundheit 97%. Alle Software-Updates durchgeführt.',
    price: 37900,
    status: 'live',
    platform: ['mobile.de'],
    images: [],
    priceCategory: 'sehr_gut',
    marketPrice: 39800,
    aiGenerated: true,
    aiConfidence: 88,
    createdAt: '2026-02-21',
    updatedAt: '2026-02-21',
    views: 567,
    inquiries: 15,
  },
  {
    id: 'l3',
    vehicleId: 'v8',
    title: 'Mercedes-Benz GLC 300 4MATIC AMG-Line',
    description: '',
    price: 52900,
    status: 'entwurf',
    platform: [],
    images: [],
    priceCategory: 'zufriedenstellend',
    marketPrice: 51500,
    aiGenerated: false,
    aiConfidence: 0,
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
    views: 0,
    inquiries: 0,
  },
  {
    id: 'l4',
    vehicleId: 'v12',
    title: 'BMW iX xDrive50 - Vollausstattung, HUD, Harman Kardon',
    description: 'Beeindruckender BMW iX xDrive50 in Mineralweiß mit nahezu Vollausstattung. Driving Assistant Professional, Head-Up Display, Harman Kardon Surround Sound, Panorama-Glasdach, Gestiksteuerung. Reichweite über 600km.',
    price: 69900,
    status: 'live',
    platform: ['mobile.de', 'autoscout24'],
    images: [],
    priceCategory: 'gut',
    marketPrice: 73500,
    aiGenerated: true,
    aiConfidence: 95,
    createdAt: '2026-02-14',
    updatedAt: '2026-02-14',
    views: 892,
    inquiries: 22,
  },
]

// ============================================
// Nachrichten
// ============================================

export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    customerName: 'Max Mustermann',
    customerPhone: '+49 176 12345678',
    channel: 'whatsapp',
    label: 'Marketing',
    inbox: 'Marketing',
    status: 'offen',
    lastMessage: 'Ist der BMW 320d noch verfügbar?',
    lastMessageAt: '2026-03-04T11:30:00',
    unread: true,
    unreadCount: 2,
    assignedTo: 'Thomas Müller',
    vehicleInterest: 'BMW 320d Touring',
    messages: [
      { id: 'm1', conversationId: 'conv1', content: 'Hallo, ich habe den BMW 320d Touring auf mobile.de gesehen.', sender: 'customer', senderName: 'Max Mustermann', timestamp: '2026-03-04T11:00:00', read: true, channel: 'whatsapp' },
      { id: 'm2', conversationId: 'conv1', content: 'Guten Tag Herr Mustermann! Ja, der BMW ist aktuell bei uns im Haus. Möchten Sie eine Probefahrt vereinbaren?', sender: 'advisor', senderName: 'Thomas Müller', timestamp: '2026-03-04T11:15:00', read: true, channel: 'whatsapp' },
      { id: 'm3', conversationId: 'conv1', content: 'Ist der BMW 320d noch verfügbar?', sender: 'customer', senderName: 'Max Mustermann', timestamp: '2026-03-04T11:30:00', read: false, channel: 'whatsapp' },
      { id: 'm4', conversationId: 'conv1', content: 'Kann ich am Samstag vorbeikommen?', sender: 'customer', senderName: 'Max Mustermann', timestamp: '2026-03-04T11:31:00', read: false, channel: 'whatsapp' },
    ],
  },
  {
    id: 'conv2',
    customerName: 'Sabine Richter',
    customerEmail: 'sabine.richter@email.de',
    channel: 'email',
    inbox: 'Zentrale',
    status: 'offen',
    lastMessage: 'Können Sie mir die Finanzierungsoptionen für den GLC zusenden?',
    lastMessageAt: '2026-03-04T10:00:00',
    unread: true,
    unreadCount: 1,
    assignedTo: 'Sarah Weber',
    vehicleInterest: 'Mercedes GLC 300',
    messages: [
      { id: 'm5', conversationId: 'conv2', content: 'Sehr geehrte Damen und Herren, ich interessiere mich für den Mercedes GLC 300 4MATIC (Angebots-Nr. 8901). Können Sie mir die Finanzierungsoptionen zusenden?', sender: 'customer', senderName: 'Sabine Richter', timestamp: '2026-03-04T10:00:00', read: false, channel: 'email' },
    ],
  },
  {
    id: 'conv3',
    customerName: 'Oliver Hartmann',
    customerPhone: '+49 172 98765432',
    channel: 'sms',
    inbox: 'Zentrale',
    status: 'spaeter',
    lastMessage: 'Danke für die Info, ich melde mich nächste Woche.',
    lastMessageAt: '2026-03-03T16:45:00',
    unread: false,
    unreadCount: 0,
    assignedTo: 'Lisa Kramer',
    vehicleInterest: 'Tesla Model 3',
    messages: [
      { id: 'm6', conversationId: 'conv3', content: 'Hallo, was ist der letzte Preis für den Tesla Model 3?', sender: 'customer', senderName: 'Oliver Hartmann', timestamp: '2026-03-03T15:00:00', read: true, channel: 'sms' },
      { id: 'm7', conversationId: 'conv3', content: 'Hallo Herr Hartmann, der Preis ist 37.900€. Bei Barzahlung können wir über einen Nachlass sprechen.', sender: 'advisor', senderName: 'Lisa Kramer', timestamp: '2026-03-03T15:30:00', read: true, channel: 'sms' },
      { id: 'm8', conversationId: 'conv3', content: 'Danke für die Info, ich melde mich nächste Woche.', sender: 'customer', senderName: 'Oliver Hartmann', timestamp: '2026-03-03T16:45:00', read: true, channel: 'sms' },
    ],
  },
  {
    id: 'conv4',
    customerName: 'Frank Schulze',
    channel: 'mobile_de',
    inbox: 'Vertrieb',
    status: 'offen',
    lastMessage: 'Anfrage zu Audi A4 Avant - Ist Preis verhandelbar?',
    lastMessageAt: '2026-03-04T09:20:00',
    unread: true,
    unreadCount: 1,
    vehicleInterest: 'Audi A4 Avant',
    messages: [
      { id: 'm9', conversationId: 'conv4', content: 'Anfrage zu Audi A4 Avant 40 TDI quattro (Angebots-Nr. 3456): Guten Tag, ist der Preis von 29.900€ noch verhandelbar? Ich bin sehr interessiert.', sender: 'customer', senderName: 'Frank Schulze', timestamp: '2026-03-04T09:20:00', read: false, channel: 'mobile_de' },
    ],
  },
  {
    id: 'conv5',
    customerName: 'Julia Bauer',
    customerPhone: '+49 157 11223344',
    channel: 'whatsapp',
    inbox: 'Standort Berlin',
    label: 'VIP',
    status: 'erledigt',
    lastMessage: 'Super, dann bis Donnerstag!',
    lastMessageAt: '2026-03-03T14:00:00',
    unread: false,
    unreadCount: 0,
    assignedTo: 'Thomas Müller',
    vehicleInterest: 'Porsche Cayenne',
    messages: [
      { id: 'm10', conversationId: 'conv5', content: 'Hallo, ich würde gerne den Porsche Cayenne besichtigen.', sender: 'customer', senderName: 'Julia Bauer', timestamp: '2026-03-03T12:00:00', read: true, channel: 'whatsapp' },
      { id: 'm11', conversationId: 'conv5', content: 'Guten Tag Frau Bauer! Sehr gerne. Wann passt es Ihnen? Der Cayenne ist gerade noch in der Inspektion, ab Donnerstag können wir Ihnen das Fahrzeug zeigen.', sender: 'advisor', senderName: 'Thomas Müller', timestamp: '2026-03-03T12:30:00', read: true, channel: 'whatsapp' },
      { id: 'm12', conversationId: 'conv5', content: 'Super, dann bis Donnerstag!', sender: 'customer', senderName: 'Julia Bauer', timestamp: '2026-03-03T14:00:00', read: true, channel: 'whatsapp' },
    ],
  },
  {
    id: 'conv6',
    customerName: 'Markus Weber',
    customerEmail: 'markus.weber@firma.de',
    channel: 'email',
    inbox: 'Vertrieb',
    label: 'B2B',
    status: 'offen',
    lastMessage: 'Flottenangebot für 5 Fahrzeuge',
    lastMessageAt: '2026-03-04T08:15:00',
    unread: true,
    unreadCount: 1,
    messages: [
      { id: 'm13', conversationId: 'conv6', content: 'Sehr geehrtes Wackenhut-Team, unsere Firma sucht 5 Dienstwagen (BMW/Mercedes, Mittelklasse). Können Sie uns ein Flottenangebot machen? Mit freundlichen Grüßen, Markus Weber, Weber GmbH', sender: 'customer', senderName: 'Markus Weber', timestamp: '2026-03-04T08:15:00', read: false, channel: 'email' },
    ],
  },
  {
    id: 'conv7',
    customerName: 'Petra Lange',
    customerPhone: '+49 160 55667788',
    channel: 'whatsapp',
    inbox: 'Marketing',
    label: 'Marketing',
    status: 'erledigt',
    lastMessage: 'Vielen Dank für die schnelle Antwort!',
    lastMessageAt: '2026-03-04T07:50:00',
    unread: false,
    unreadCount: 0,
    assignedTo: 'Sarah Weber',
    vehicleInterest: 'VW Golf GTI',
    messages: [
      { id: 'm14', conversationId: 'conv7', content: 'Gibt es den Golf GTI auch in Schwarz?', sender: 'customer', senderName: 'Petra Lange', timestamp: '2026-03-04T07:30:00', read: true, channel: 'whatsapp' },
      { id: 'm15', conversationId: 'conv7', content: 'Guten Morgen Frau Lange! Aktuell haben wir den GTI nur in Tornadorot. Soll ich Sie informieren wenn ein schwarzer reinkommt?', sender: 'advisor', senderName: 'Sarah Weber', timestamp: '2026-03-04T07:45:00', read: true, channel: 'whatsapp' },
      { id: 'm16', conversationId: 'conv7', content: 'Vielen Dank für die schnelle Antwort!', sender: 'customer', senderName: 'Petra Lange', timestamp: '2026-03-04T07:50:00', read: true, channel: 'whatsapp' },
    ],
  },
  {
    id: 'conv8',
    customerName: 'Leon Fischer',
    channel: 'messenger',
    inbox: 'Zentrale',
    status: 'offen',
    lastMessage: 'Top, vielen Dank noch einmal!',
    lastMessageAt: '2026-03-04T15:49:00',
    unread: false,
    unreadCount: 0,
    assignedTo: 'Thomas Müller',
    vehicleInterest: 'Audi e-tron GT',
    messages: [
      { id: 'm17', conversationId: 'conv8', content: 'Hey, ich habe euren Audi e-tron GT auf Instagram gesehen – wahnsinnig schönes Auto! Ist das noch zu haben?', sender: 'customer', senderName: 'Leon Fischer', timestamp: '2026-03-04T15:20:00', read: true, channel: 'messenger' },
      { id: 'm18', conversationId: 'conv8', content: 'Hallo Leon! Ja, der e-tron GT ist noch verfügbar. Ein absoluter Traum! Soll ich dir alle Infos schicken?', sender: 'advisor', senderName: 'Thomas Müller', timestamp: '2026-03-04T15:35:00', read: true, channel: 'messenger' },
      { id: 'm19', conversationId: 'conv8', content: 'Top, vielen Dank noch einmal!', sender: 'customer', senderName: 'Leon Fischer', timestamp: '2026-03-04T15:49:00', read: true, channel: 'messenger' },
    ],
  },
  {
    id: 'conv9',
    customerName: 'Hannah Becker',
    channel: 'instagram',
    inbox: 'Standort Berlin',
    label: 'Marketing',
    status: 'offen',
    lastMessage: '249€ ist noch ein bisschen teuer für d...',
    lastMessageAt: '2026-03-04T14:22:00',
    unread: true,
    unreadCount: 1,
    assignedTo: 'Sarah Weber',
    messages: [
      { id: 'm20', conversationId: 'conv9', content: 'Hey! Ich hab eure Story gesehen – habt ihr das Angebot für die Vollinspektion noch? 249€ ist noch ein bisschen teuer für das, was ihr beschreibt 😅', sender: 'customer', senderName: 'Hannah Becker', timestamp: '2026-03-04T14:22:00', read: false, channel: 'instagram' },
    ],
  },
  {
    id: 'conv10',
    customerName: 'Emma Neumann',
    channel: 'instagram',
    inbox: 'Zentrale',
    status: 'spaeter',
    lastMessage: 'Ich hatte vorgestern schon einmal dar...',
    lastMessageAt: '2026-03-04T14:03:00',
    unread: false,
    unreadCount: 0,
    messages: [
      { id: 'm21', conversationId: 'conv10', content: 'Ich hatte vorgestern schon einmal darum gebeten – könnt ihr mir das Exposé zum BMW X3 schicken?', sender: 'customer', senderName: 'Emma Neumann', timestamp: '2026-03-04T14:03:00', read: true, channel: 'instagram' },
      { id: 'm22', conversationId: 'conv10', content: 'Hallo Emma, natürlich! Ich schicke dir gleich alle Details zum BMW X3 xDrive30d. Einen Moment bitte.', sender: 'advisor', senderName: 'Sarah Weber', timestamp: '2026-03-04T14:10:00', read: true, channel: 'instagram' },
    ],
  },
  {
    id: 'conv11',
    customerName: 'Finn Krüger',
    channel: 'telegram',
    inbox: 'Marketing',
    label: 'Marketing',
    status: 'offen',
    lastMessage: 'Geht auch 10.30 Uhr morgen? Dann kö...',
    lastMessageAt: '2026-03-04T09:32:00',
    unread: true,
    unreadCount: 2,
    assignedTo: 'Lisa Kramer',
    vehicleInterest: 'VW Tiguan',
    messages: [
      { id: 'm23', conversationId: 'conv11', content: 'Hallo! Ihr habt mir heute Morgen eine Nachricht über die Aktion geschickt. Wann kann ich den Tiguan besichtigen?', sender: 'customer', senderName: 'Finn Krüger', timestamp: '2026-03-04T09:15:00', read: true, channel: 'telegram' },
      { id: 'm24', conversationId: 'conv11', content: 'Hallo Finn! Wir haben heute ab 11 Uhr Zeit. Würde das passen?', sender: 'advisor', senderName: 'Lisa Kramer', timestamp: '2026-03-04T09:25:00', read: true, channel: 'telegram' },
      { id: 'm25', conversationId: 'conv11', content: 'Geht auch 10.30 Uhr morgen? Dann könnte ich direkt meinen Bruder mitnehmen.', sender: 'customer', senderName: 'Finn Krüger', timestamp: '2026-03-04T09:32:00', read: false, channel: 'telegram' },
    ],
  },
  {
    id: 'conv12',
    customerName: 'Jakob Fuchs',
    channel: 'telegram',
    inbox: 'Zentrale',
    status: 'spaeter',
    lastMessage: 'Sehr geehrte Damen und Herren, ich h...',
    lastMessageAt: '2026-03-03T17:00:00',
    unread: false,
    unreadCount: 0,
    messages: [
      { id: 'm26', conversationId: 'conv12', content: 'Sehr geehrte Damen und Herren, ich hatte letzten Monat Kontakt bezüglich eines Leasingvertrags. Können wir das Thema erneut aufgreifen?', sender: 'customer', senderName: 'Jakob Fuchs', timestamp: '2026-03-03T17:00:00', read: true, channel: 'telegram' },
    ],
  },
]

// ============================================
// KYC
// ============================================

export const mockKYCSubmissions: KYCSubmission[] = [
  {
    id: 'kyc1',
    customerName: 'Klaus Becker',
    customerType: 'privat',
    email: 'klaus.becker@email.de',
    phone: '+49 711 5678901',
    status: 'verifiziert',
    submittedAt: '2026-03-03T10:00:00',
    reviewedAt: '2026-03-03T10:05:00',
    reviewedBy: 'System (Auto)',
    vehicleIds: ['v3'],
    privacyMethod: 'upload',
    documentType: 'personalausweis',
    documentNumber: 'L01X00T47',
    dateOfBirth: '1985-06-15',
    address: 'Königstraße 42, 70173 Stuttgart',
    checkResults: [
      { check: 'Dokumenten-Validierung', passed: true, detail: 'Personalausweis gültig bis 2028' },
      { check: 'Namensabgleich', passed: true, detail: 'Name stimmt überein' },
      { check: 'Adressverifikation', passed: true, detail: 'Adresse bestätigt' },
    ],
    documentBundle: {
      status: 'ready',
      generatedAt: '2026-03-03T10:10:00',
    },
  },
  {
    id: 'kyc2',
    customerName: 'Weber GmbH',
    customerType: 'gewerbe',
    email: 'markus.weber@firma.de',
    phone: '+49 711 9876543',
    status: 'in_pruefung',
    submittedAt: '2026-03-04T08:30:00',
    vehicleIds: ['v2', 'v6'],
    companyName: 'Weber GmbH',
    handelsregisterNr: 'HRB 123456',
    ustIdNr: 'DE123456789',
    checkResults: [
      { check: 'Handelsregister', passed: true, detail: 'Firma eingetragen, aktiv' },
      { check: 'USt-IdNr. Prüfung', passed: false, detail: 'Prüfung läuft...' },
    ],
  },
  {
    id: 'kyc3',
    customerName: 'Anna Hoffmann',
    customerType: 'privat',
    email: 'anna.hoffmann@email.de',
    phone: '+49 711 4567890',
    status: 'eingereicht',
    submittedAt: '2026-03-04T09:45:00',
    vehicleIds: ['v4'],
    privacyMethod: 'link',
    documentType: 'reisepass',
    documentNumber: 'C01X00T23',
    dateOfBirth: '1992-03-22',
    address: 'Schlossstraße 15, 70174 Stuttgart',
  },
  {
    id: 'kyc4',
    customerName: 'Frank Schulze',
    customerType: 'privat',
    email: 'frank.schulze@email.de',
    phone: '+49 711 3456789',
    status: 'manuell_pruefen',
    submittedAt: '2026-03-03T14:00:00',
    vehicleIds: ['v1'],
    privacyMethod: 'upload',
    documentType: 'personalausweis',
    documentNumber: 'T04X00R89',
    dateOfBirth: '1978-11-08',
    address: 'Marienplatz 7, 70178 Stuttgart',
    checkResults: [
      { check: 'Dokumenten-Validierung', passed: true, detail: 'Personalausweis gültig' },
      { check: 'Namensabgleich', passed: true, detail: 'Name stimmt überein' },
      { check: 'Adressverifikation', passed: false, detail: 'Adresse weicht ab - manuell prüfen' },
    ],
    notes: 'Adresse auf Ausweis ist alte Adresse, Kunde ist umgezogen',
  },
  {
    id: 'kyc5',
    customerName: 'Autohaus Partner KG',
    customerType: 'gewerbe',
    email: 'info@autopartner.de',
    phone: '+49 711 1112233',
    status: 'abgelehnt',
    submittedAt: '2026-03-02T11:00:00',
    reviewedAt: '2026-03-02T11:10:00',
    reviewedBy: 'System (Auto)',
    vehicleIds: ['v5'],
    companyName: 'Autohaus Partner KG',
    handelsregisterNr: 'HRA 999999',
    ustIdNr: 'DE999999999',
    checkResults: [
      { check: 'Handelsregister', passed: false, detail: 'Firma nicht gefunden' },
      { check: 'USt-IdNr. Prüfung', passed: false, detail: 'USt-IdNr. ungültig' },
    ],
    notes: 'Alle Angaben fehlerhaft',
  },
]

// ============================================
// Buchhaltung
// ============================================

export const mockAccountingDocuments: AccountingDocument[] = [
  {
    id: 'acc-doc-1',
    month: '2026-03',
    vehicleId: 'v1',
    type: 'eingangsrechnung',
    status: 'freigabe_noetig',
    paymentStatus: 'bezahlt',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'ER-2026-0315',
    invoiceDate: '2026-03-01',
    partnerName: 'Autohaus Nord GmbH',
    netAmount: 23949.58,
    vatAmount: 4550.42,
    grossAmount: 28500,
    currency: 'EUR',
    pdfUrl: '/demo-docs/eingangsrechnung-bmw.pdf',
    aiConfidence: 96,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'ER-2026-0315', confidence: 99, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '01.03.2026', confidence: 98, required: true },
      { key: 'partnerName', label: 'Lieferant', value: 'Autohaus Nord GmbH', confidence: 96, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'BMW 320d Touring (S-WH 1234)', confidence: 95, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '28.500,00 EUR', confidence: 99, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 97, required: true },
    ],
    bookingProposal: {
      kontoSoll: '3200 Wareneingang Fahrzeuge',
      kontoHaben: '70000 Verbindlichkeiten',
      steuerSchluessel: 'V19',
      netto: 23949.58,
      ust: 4550.42,
      brutto: 28500,
    },
    flags: [],
    createdAt: '2026-03-01T09:10:00',
    updatedAt: '2026-03-01T09:14:00',
  },
  {
    id: 'acc-doc-2',
    month: '2026-03',
    vehicleId: 'v1',
    type: 'ausgangsrechnung',
    status: 'ki_extrahiert',
    paymentStatus: 'offen',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'AR-2026-1187',
    invoiceDate: '2026-03-04',
    partnerName: 'Klaus Becker',
    netAmount: 29327.73,
    vatAmount: 5572.27,
    grossAmount: 34900,
    currency: 'EUR',
    pdfUrl: '/demo-docs/ausgangsrechnung-bmw.pdf',
    aiConfidence: 91,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'AR-2026-1187', confidence: 98, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '04.03.2026', confidence: 97, required: true },
      { key: 'partnerName', label: 'Kunde', value: 'Klaus Becker', confidence: 95, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'BMW 320d Touring (S-WH 1234)', confidence: 94, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '34.900,00 EUR', confidence: 99, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 88, required: true },
    ],
    bookingProposal: {
      kontoSoll: '1200 Forderungen',
      kontoHaben: '8400 Erlöse 19%',
      steuerSchluessel: 'U19',
      netto: 29327.73,
      ust: 5572.27,
      brutto: 34900,
    },
    flags: [
      { id: 'flag-acc2-1', code: 'LOW_CONF_TAXMODE', severity: 'warn', message: 'Steuerart mit niedriger KI-Sicherheit erkannt.', resolved: false },
    ],
    createdAt: '2026-03-04T10:08:00',
    updatedAt: '2026-03-04T10:10:00',
  },
  {
    id: 'acc-doc-3',
    month: '2026-03',
    vehicleId: 'v2',
    type: 'eingangsrechnung',
    status: 'freigegeben',
    paymentStatus: 'bezahlt',
    taxMode: 'differenzbesteuerung_25a',
    invoiceNumber: 'ER-2026-0322',
    invoiceDate: '2026-03-02',
    partnerName: 'Privatankauf Süd',
    netAmount: 31200,
    vatAmount: 0,
    grossAmount: 31200,
    currency: 'EUR',
    pdfUrl: '/demo-docs/eingangsrechnung-mercedes.pdf',
    aiConfidence: 95,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'ER-2026-0322', confidence: 98, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '02.03.2026', confidence: 97, required: true },
      { key: 'partnerName', label: 'Lieferant', value: 'Privatankauf Süd', confidence: 94, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'Mercedes-Benz C 200 (S-WH 2345)', confidence: 95, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '31.200,00 EUR', confidence: 98, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Differenzbesteuerung §25a', confidence: 92, required: true },
    ],
    bookingProposal: {
      kontoSoll: '3200 Wareneingang Fahrzeuge',
      kontoHaben: '70000 Verbindlichkeiten',
      steuerSchluessel: 'D25',
      netto: 31200,
      ust: 0,
      brutto: 31200,
    },
    flags: [],
    createdAt: '2026-03-02T13:20:00',
    updatedAt: '2026-03-02T13:32:00',
  },
  {
    id: 'acc-doc-4',
    month: '2026-03',
    vehicleId: 'v2',
    type: 'ausgangsrechnung',
    status: 'freigabe_noetig',
    paymentStatus: 'offen',
    taxMode: 'differenzbesteuerung_25a',
    invoiceNumber: 'AR-2026-1199',
    invoiceDate: '2026-03-04',
    partnerName: 'Autohaus Partner KG',
    netAmount: 38500,
    vatAmount: 0,
    grossAmount: 38500,
    currency: 'EUR',
    pdfUrl: '/demo-docs/ausgangsrechnung-mercedes.pdf',
    aiConfidence: 87,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'AR-2026-1199', confidence: 99, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '04.03.2026', confidence: 98, required: true },
      { key: 'partnerName', label: 'Kunde', value: 'Autohaus Partner KG', confidence: 93, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'Mercedes-Benz C 200 (S-WH 2345)', confidence: 90, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '38.500,00 EUR', confidence: 99, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Differenzbesteuerung §25a', confidence: 81, required: true },
    ],
    bookingProposal: {
      kontoSoll: '1200 Forderungen',
      kontoHaben: '8320 Erlöse Diff.-besteuert',
      steuerSchluessel: 'D25',
      netto: 38500,
      ust: 0,
      brutto: 38500,
    },
    flags: [
      { id: 'flag-acc4-1', code: 'PLAUSIBILITY_MARGIN', severity: 'warn', message: 'Marge weicht stark vom Durchschnitt ab. Bitte prüfen.', resolved: false },
    ],
    createdAt: '2026-03-04T15:40:00',
    updatedAt: '2026-03-04T15:42:00',
  },
  {
    id: 'acc-doc-5',
    month: '2026-03',
    vehicleId: null,
    type: 'eingangsrechnung',
    status: 'fehler',
    paymentStatus: 'ueberfaellig',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'ER-2026-0401',
    invoiceDate: '2026-03-04',
    partnerName: 'Werkstatt Huber GmbH',
    netAmount: 1260.5,
    vatAmount: 239.5,
    grossAmount: 1500,
    currency: 'EUR',
    pdfUrl: '/demo-docs/eingangsrechnung-bmw.pdf',
    aiConfidence: 76,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'ER-2026-0401', confidence: 96, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '04.03.2026', confidence: 95, required: true },
      { key: 'partnerName', label: 'Lieferant', value: 'Werkstatt Huber GmbH', confidence: 93, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'Nicht erkannt', confidence: 22, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '1.500,00 EUR', confidence: 97, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 88, required: true },
    ],
    bookingProposal: {
      kontoSoll: '3400 Bezogene Leistungen',
      kontoHaben: '70000 Verbindlichkeiten',
      steuerSchluessel: 'V19',
      netto: 1260.5,
      ust: 239.5,
      brutto: 1500,
    },
    flags: [
      { id: 'flag-acc5-1', code: 'MISSING_VEHICLE', severity: 'critical', message: 'Fehlende Fahrzeugzuordnung.', resolved: false },
    ],
    createdAt: '2026-03-04T16:11:00',
    updatedAt: '2026-03-04T16:13:00',
  },
  {
    id: 'acc-doc-6',
    month: '2026-03',
    vehicleId: 'v3',
    type: 'ausgangsrechnung',
    status: 'freigabe_noetig',
    paymentStatus: 'offen',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'AR-2026-1187',
    invoiceDate: '2026-03-04',
    partnerName: 'Anna Hoffmann',
    netAmount: 25126.05,
    vatAmount: 4773.95,
    grossAmount: 29900,
    currency: 'EUR',
    pdfUrl: '/demo-docs/ausgangsrechnung-bmw.pdf',
    aiConfidence: 89,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'AR-2026-1187', confidence: 99, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '04.03.2026', confidence: 98, required: true },
      { key: 'partnerName', label: 'Kunde', value: 'Anna Hoffmann', confidence: 95, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'Audi A4 Avant (S-WH 3456)', confidence: 96, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '29.900,00 EUR', confidence: 98, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 84, required: true },
    ],
    bookingProposal: {
      kontoSoll: '1200 Forderungen',
      kontoHaben: '8400 Erlöse 19%',
      steuerSchluessel: 'U19',
      netto: 25126.05,
      ust: 4773.95,
      brutto: 29900,
    },
    flags: [
      { id: 'flag-acc6-1', code: 'DUPLICATE_INVOICE_NO', severity: 'critical', message: 'Doppelte Rechnungsnummer erkannt (AR-2026-1187).', resolved: false },
    ],
    createdAt: '2026-03-04T17:05:00',
    updatedAt: '2026-03-04T17:08:00',
  },
  {
    id: 'acc-doc-7',
    month: '2026-03',
    vehicleId: 'v4',
    type: 'eingangsrechnung',
    status: 'gebucht',
    paymentStatus: 'bezahlt',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'ER-2026-0291',
    invoiceDate: '2026-03-03',
    partnerName: 'Autohaus Mitte AG',
    netAmount: 24705.88,
    vatAmount: 4694.12,
    grossAmount: 29400,
    currency: 'EUR',
    pdfUrl: '/demo-docs/eingangsrechnung-mercedes.pdf',
    aiConfidence: 97,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'ER-2026-0291', confidence: 99, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '03.03.2026', confidence: 99, required: true },
      { key: 'partnerName', label: 'Lieferant', value: 'Autohaus Mitte AG', confidence: 97, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'VW Golf 8 GTI (S-WH 4567)', confidence: 98, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '29.400,00 EUR', confidence: 99, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 98, required: true },
    ],
    bookingProposal: {
      kontoSoll: '3200 Wareneingang Fahrzeuge',
      kontoHaben: '70000 Verbindlichkeiten',
      steuerSchluessel: 'V19',
      netto: 24705.88,
      ust: 4694.12,
      brutto: 29400,
    },
    flags: [],
    createdAt: '2026-03-03T10:30:00',
    updatedAt: '2026-03-03T10:35:00',
  },
  {
    id: 'acc-doc-8',
    month: '2026-03',
    vehicleId: 'v4',
    type: 'ausgangsrechnung',
    status: 'gebucht',
    paymentStatus: 'bezahlt',
    taxMode: 'regelbesteuerung_19',
    invoiceNumber: 'AR-2026-1172',
    invoiceDate: '2026-03-04',
    partnerName: 'Finn Krüger',
    netAmount: 30168.07,
    vatAmount: 5731.93,
    grossAmount: 35900,
    currency: 'EUR',
    pdfUrl: '/demo-docs/ausgangsrechnung-mercedes.pdf',
    aiConfidence: 96,
    extractionFields: [
      { key: 'invoiceNumber', label: 'Rechnungsnummer', value: 'AR-2026-1172', confidence: 99, required: true },
      { key: 'invoiceDate', label: 'Rechnungsdatum', value: '04.03.2026', confidence: 98, required: true },
      { key: 'partnerName', label: 'Kunde', value: 'Finn Krüger', confidence: 96, required: true },
      { key: 'vehicleRef', label: 'Fahrzeug', value: 'VW Golf 8 GTI (S-WH 4567)', confidence: 97, required: true },
      { key: 'grossAmount', label: 'Brutto', value: '35.900,00 EUR', confidence: 99, required: true },
      { key: 'taxMode', label: 'Steuerart', value: 'Regelbesteuerung 19%', confidence: 97, required: true },
    ],
    bookingProposal: {
      kontoSoll: '1200 Forderungen',
      kontoHaben: '8400 Erlöse 19%',
      steuerSchluessel: 'U19',
      netto: 30168.07,
      ust: 5731.93,
      brutto: 35900,
    },
    flags: [],
    createdAt: '2026-03-04T12:10:00',
    updatedAt: '2026-03-04T12:18:00',
  },
]

export const mockVehicleAccountingCases: VehicleAccountingCase[] = [
  {
    id: 'acc-case-1',
    month: '2026-03',
    vehicleId: 'v1',
    incomingDocumentId: 'acc-doc-1',
    outgoingDocumentId: 'acc-doc-2',
    hasIncomingInvoice: true,
    hasOutgoingInvoice: true,
    taxMode: 'regelbesteuerung_19',
    purchaseAmount: 28500,
    saleAmount: 34900,
    marginAmount: 6400,
    vatAmount: 5572.27,
    status: 'exportbereit',
    blockers: [],
  },
  {
    id: 'acc-case-2',
    month: '2026-03',
    vehicleId: 'v2',
    incomingDocumentId: 'acc-doc-3',
    outgoingDocumentId: 'acc-doc-4',
    hasIncomingInvoice: true,
    hasOutgoingInvoice: true,
    taxMode: 'differenzbesteuerung_25a',
    purchaseAmount: 31200,
    saleAmount: 38500,
    marginAmount: 7300,
    vatAmount: 0,
    status: 'pruefung',
    blockers: ['Differenzbesteuerung prüfen: Marge auffällig hoch.'],
  },
  {
    id: 'acc-case-3',
    month: '2026-03',
    vehicleId: 'v3',
    incomingDocumentId: 'acc-doc-5',
    outgoingDocumentId: 'acc-doc-6',
    hasIncomingInvoice: false,
    hasOutgoingInvoice: true,
    taxMode: 'regelbesteuerung_19',
    saleAmount: 29900,
    vatAmount: 4773.95,
    status: 'offen',
    blockers: ['Eingangsrechnung fehlt oder nicht zugeordnet.', 'Doppelte Rechnungsnummer erkannt.'],
  },
  {
    id: 'acc-case-4',
    month: '2026-03',
    vehicleId: 'v4',
    incomingDocumentId: 'acc-doc-7',
    outgoingDocumentId: 'acc-doc-8',
    hasIncomingInvoice: true,
    hasOutgoingInvoice: true,
    taxMode: 'regelbesteuerung_19',
    purchaseAmount: 29400,
    saleAmount: 35900,
    marginAmount: 6500,
    vatAmount: 5731.93,
    status: 'exportiert',
    blockers: [],
  },
]

export const mockAccountingExportBatches: AccountingExportBatch[] = [
  {
    id: 'acc-batch-1',
    month: '2026-02',
    status: 'erstellt',
    createdAt: '2026-03-01T09:30:00',
    createdBy: 'Thomas M.',
    documentCount: 14,
    totals: {
      net: 351260.44,
      vat: 42231.47,
      gross: 393491.91,
    },
    datevCsvUrl: '/demo-docs/datev-export-2026-03.csv',
    belegZipUrl: '/demo-docs/belegpaket-2026-03.zip',
    protocolUrl: '/demo-docs/datev-export-2026-03.csv',
  },
  {
    id: 'acc-batch-2',
    month: '2026-03',
    status: 'bereit',
    createdAt: '2026-03-05T08:00:00',
    createdBy: 'Thomas M.',
    documentCount: 8,
    totals: {
      net: 191237.81,
      vat: 25562.19,
      gross: 216800,
    },
    datevCsvUrl: '/demo-docs/datev-export-2026-03.csv',
    belegZipUrl: '/demo-docs/belegpaket-2026-03.zip',
    protocolUrl: '/demo-docs/datev-export-2026-03.csv',
  },
]

// ============================================
// Dashboard Stats
// ============================================

export const mockDashboardStats: DashboardStats = {
  werkstatt: { wartend: 4, ueberfaellig: 2 },
  rueckrufe: { offen: 5, ueberfaellig: 2 },
  inserate: { zuErstellen: 3, zuVeroeffentlichen: 5 },
  nachrichten: { ungelesen: 8, heuteNeu: 12 },
  kyc: { offen: 3, zuPruefen: 1 },
  buchhaltung: { offen: 5, kritisch: 2 },
}

export const mockActivity: ActivityEntry[] = [
  {
    id: 'act0',
    module: 'buchhaltung',
    action: 'Buchung blockiert',
    subject: 'Audi A4 Avant 40 TDI',
    description: 'Doppelte Rechnungsnummer erkannt',
    user: 'KI Buchhaltung',
    timestamp: '2026-03-05T08:10:00',
    link: '/buchhaltung',
    details: [
      { label: 'Fahrzeug', value: 'Audi A4 Avant 40 TDI' },
      { label: 'Rechnung', value: 'AR-2026-1187' },
      { label: 'Flag', value: 'DUPLICATE_INVOICE_NO' },
      { label: 'Status', value: 'Manuelle Prüfung notwendig' },
    ],
  },
  {
    id: 'act1',
    module: 'werkstatt',
    action: 'Status geändert',
    subject: 'BMW 320d xDrive',
    description: 'Inspektion → Werkstatt',
    user: 'Michael S.',
    timestamp: '2026-03-04T11:30:00',
    link: '/fahrzeuge/werkstatt',
    details: [
      { label: 'Fahrzeug', value: 'BMW 320d xDrive (2023)' },
      { label: 'Kennzeichen', value: 'S-WH 1234' },
      { label: 'Alter Status', value: 'Inspektion' },
      { label: 'Neuer Status', value: 'Werkstatt' },
    ],
  },
  {
    id: 'act2',
    module: 'callcenter',
    action: 'Rückruf erledigt',
    subject: 'Klaus Becker',
    description: 'Abholtermin vereinbart',
    user: 'Lisa K.',
    timestamp: '2026-03-04T08:20:00',
    link: '/callcenter',
    details: [
      { label: 'Kunde', value: 'Klaus Becker' },
      { label: 'Telefon', value: '+49 711 123456' },
      { label: 'Grund', value: 'Abholtermin' },
      { label: 'Berater', value: 'Lisa K.' },
    ],
  },
  {
    id: 'act3',
    module: 'inserate',
    action: 'Inserat veröffentlicht',
    subject: 'Audi A4 Avant 40 TDI',
    description: 'Auf mobile.de und AutoScout24',
    user: 'Thomas M.',
    timestamp: '2026-03-04T10:15:00',
    link: '/inserate',
    details: [
      { label: 'Fahrzeug', value: 'Audi A4 Avant 40 TDI (2024)' },
      { label: 'Preis', value: '42.900 €' },
      { label: 'Plattformen', value: 'mobile.de, AutoScout24' },
      { label: 'KI-generiert', value: 'Ja (95% Confidence)' },
    ],
  },
  {
    id: 'act4',
    module: 'nachrichten',
    action: 'Neue Nachricht',
    subject: 'Max Mustermann',
    description: 'WhatsApp — Anfrage zu BMW 520d Touring',
    user: 'System',
    timestamp: '2026-03-04T11:30:00',
    link: '/nachrichten',
    details: [
      { label: 'Kunde', value: 'Max Mustermann' },
      { label: 'Kanal', value: 'WhatsApp' },
      { label: 'Interesse', value: 'BMW 520d Touring' },
      { label: 'Nachricht', value: 'Ist der BMW 520d noch verfügbar?' },
    ],
  },
  {
    id: 'act5',
    module: 'kyc',
    action: 'Verifiziert',
    subject: 'Klaus Becker',
    description: 'KYC automatisch bestanden',
    user: 'System',
    timestamp: '2026-03-03T10:05:00',
    link: '/verifizierung',
    details: [
      { label: 'Kunde', value: 'Klaus Becker' },
      { label: 'Kundentyp', value: 'Privat' },
      { label: 'Prüfmethode', value: 'Automatisch' },
      { label: 'Ergebnis', value: 'Alle Dokumente gültig' },
    ],
  },
  {
    id: 'act6',
    module: 'nachrichten',
    action: 'Neue Anfrage',
    subject: 'Weber GmbH',
    description: 'Flottenangebot für 5 Fahrzeuge',
    user: 'System',
    timestamp: '2026-03-04T08:15:00',
    link: '/nachrichten',
    details: [
      { label: 'Firma', value: 'Weber GmbH' },
      { label: 'Kanal', value: 'E-Mail' },
      { label: 'Interesse', value: 'Flottenangebot' },
      { label: 'Anzahl', value: '5 Fahrzeuge' },
    ],
  },
  {
    id: 'act7',
    module: 'werkstatt',
    action: 'Fahrzeug eingegangen',
    subject: 'Audi e-tron GT',
    description: 'Neues Fahrzeug — Inspektion eingeleitet',
    user: 'Thomas M.',
    timestamp: '2026-03-04T08:00:00',
    link: '/fahrzeuge/werkstatt',
    details: [
      { label: 'Fahrzeug', value: 'Audi e-tron GT (2025)' },
      { label: 'Kilometerstand', value: '12.500 km' },
      { label: 'Standort', value: 'Hof A' },
      { label: 'Nächster Schritt', value: 'Inspektion' },
    ],
  },
  {
    id: 'act8',
    module: 'callcenter',
    action: 'Neuer Rückruf',
    subject: 'Hans Gruber',
    description: 'Probefahrt — Mercedes C 300 AMG Line',
    user: 'Callcenter',
    timestamp: '2026-03-04T09:15:00',
    link: '/callcenter',
    details: [
      { label: 'Kunde', value: 'Hans Gruber' },
      { label: 'Telefon', value: '+49 711 654321' },
      { label: 'Grund', value: 'Probefahrt' },
      { label: 'Fahrzeug', value: 'Mercedes C 300 AMG Line' },
    ],
  },
]
